# Generated by Django 4.2.9 on 2024-04-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[
                            (1, "rating__rating_choices__hate"),
                            (2, "rating__rating_choices__dislike"),
                            (3, "rating__rating_choices__neutral"),
                            (4, "rating__rating_choices__like"),
                            (5, "rating__rating_choices__love"),
                        ],
                        verbose_name="feedback__model__rate__value",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="model__foreign__author",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="recipes.recipe",
                        verbose_name="model__foreign__recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback__model__rate__verbose_name",
                "verbose_name_plural": "feedback__model__rate__verbose_name_plural",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="model__created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="model__updated"
                    ),
                ),
                (
                    "text",
                    mdeditor.fields.MDTextField(
                        max_length=2047,
                        verbose_name="feedback__model__comment__text",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="model__foreign__author",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="recipes.recipe",
                        verbose_name="model__foreign__recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback__model__comment__verbose_name",
                "verbose_name_plural": "feedback__model__comment__verbose_name_plural",
            },
        ),
    ]
