# Generated by Django 4.2.9 on 2024-04-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0003_recipeimage_alter_category_options_and_more"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cooked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="model__foreign__author",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooked",
                        to="recipes.recipe",
                        verbose_name="model__foreign__recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback__model__cooked__verbose_name",
                "verbose_name_plural": "feedback__model__cooked__verbose_name_plural",
                "unique_together": {("author", "recipe")},
            },
        ),
    ]
