# Generated by Django 4.2.9 on 2024-04-11 20:28

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127,
                        verbose_name="recipes__model__category__name",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__category__verbose_name",
                "verbose_name_plural": "recipes__model__category__verbose_name_plural",
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127,
                        verbose_name="recipes__model__ingredient__name",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__ingredient__verbose_name",
                "verbose_name_plural": "recipes__model__ingredient__verbose_name_plural",
            },
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=127,
                        verbose_name="recipes__model__kitchen__name",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__kitchen__verbose_name",
                "verbose_name_plural": "recipes__model__kitchen__verbose_name_plural",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="recipes__model__recipe__title",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="model__created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="model__updated"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PUB", "recipes__recipe_state__published"),
                            ("MOD", "recipes__recipe_state__moderated"),
                            ("REJ", "recipes__recipe_state__rejected"),
                        ],
                        default="MOD",
                        max_length=3,
                        verbose_name="recipes__model__recipe__state",
                    ),
                ),
                (
                    "instruction",
                    mdeditor.fields.MDTextField(
                        max_length=8191,
                        verbose_name="recipes__model__recipe__instruction",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.RandomFileName(
                            "recipes/main_image/"
                        ),
                        verbose_name="recipes__model__recipe__main_image",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "recipes__level_choices__easy"),
                            (2, "recipes__level_choices__normal"),
                            (3, "recipes__level_choices__hard"),
                            (4, "recipes__level_choices__extreme"),
                        ],
                        verbose_name="recipes__model__recipe__level",
                    ),
                ),
                (
                    "time",
                    models.PositiveIntegerField(
                        verbose_name="recipes__model__recipe__time"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="model__foreign__author",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipes",
                        to="recipes.category",
                        verbose_name="model__foreign__categories",
                    ),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes",
                        to="recipes.kitchen",
                        verbose_name="model__foreign__kitchen",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__recipe__verbose_name",
                "verbose_name_plural": "recipes__model__recipe__verbose_name_plural",
            },
        ),
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.utils.RandomFileName(
                            "recipes/additional/"
                        ),
                        verbose_name="recipes__model__additional_image__image",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="recipes.recipe",
                        verbose_name="model__foreign__recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__additional_image__verbose_name",
                "verbose_name_plural": "recipes__model__additional_image__verbose_name_plural",
                "db_table": "additional_image",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="recipes__model__recipe_ingredient__count",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("G", "recipes__unit_choices__grams"),
                            ("KG", "recipes__unit_choices__kilogramme"),
                            ("L", "recipes__unit_choices__litre"),
                            ("ML", "recipes__unit_choices__millilitre"),
                            ("PIECE", "recipes__unit_choices__piece"),
                            ("PINCH", "recipes__unit_choices__pinch"),
                            ("TEASPOON", "recipes__unit_choices__tea_spoon"),
                            (
                                "TABLESPOON",
                                "recipes__unit_choices__table_spoon",
                            ),
                            ("4", "recipes__level_choices__extreme"),
                        ],
                        max_length=12,
                        verbose_name="recipes__model__recipe_ingredient__unit",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                        verbose_name="model__foreign__ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                        verbose_name="model__foreign__recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__recipe_ingredient__verbose_name",
                "verbose_name_plural": "recipes__model__recipe_ingredient__verbose_name_plural",
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
