# Generated by Django 4.2.9 on 2024-04-12 14:58

from django.db import migrations, models

from core.utils import normalize_name


def normalize_names(apps, schema_editor):
    models = [
        "Category",
        "Ingredient",
        "Kitchen",
        "Recipe",
    ]
    for model in models:
        objs = apps.get_model("recipes", model)
        for obj in objs.objects.all():
            obj.normalized_name = normalize_name(obj.name)
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="kitchen",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, null=True),
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("G", "recipes__unit_choices__grams"),
                    ("KG", "recipes__unit_choices__kilogramme"),
                    ("L", "recipes__unit_choices__litre"),
                    ("ML", "recipes__unit_choices__millilitre"),
                    ("PIECE", "recipes__unit_choices__piece"),
                    ("PINCH", "recipes__unit_choices__pinch"),
                    ("TEASPOON", "recipes__unit_choices__tea_spoon"),
                    ("TABLESPOON", "recipes__unit_choices__table_spoon"),
                    ("CUP", "recipes__unit_choices__cup"),
                ],
                max_length=12,
                verbose_name="recipes__model__recipe_ingredient__unit",
            ),
        ),
        migrations.RunPython(normalize_names),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="kitchen",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="kitchen",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127),
        ),
    ]
