# Generated by Django 4.2.9 on 2024-04-13 14:28

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_remove_recipe_title_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.utils.RandomFileName("recipes/recipe/"),
                        verbose_name="recipes__model__recipe_image__image",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipes__model__recipe_image__verbose_name",
                "verbose_name_plural": "recipes__model__recipe_image__verbose_name_plural",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "recipes__model__category__verbose_name",
                "verbose_name_plural": "recipes__model__category__verbose_name_plural",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "recipes__model__ingredient__verbose_name",
                "verbose_name_plural": "recipes__model__ingredient__verbose_name_plural",
            },
        ),
        migrations.AlterModelOptions(
            name="kitchen",
            options={
                "ordering": ["name"],
                "verbose_name": "recipes__model__kitchen__verbose_name",
                "verbose_name_plural": "recipes__model__kitchen__verbose_name_plural",
            },
        ),
        migrations.AlterField(
            model_name="kitchen",
            name="normalized_name",
            field=models.CharField(
                editable=False, max_length=127, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="recipes__model__recipe__name"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="normalized_name",
            field=models.CharField(editable=False, max_length=127),
        ),
        migrations.DeleteModel(
            name="AdditionalImage",
        ),
        migrations.AddField(
            model_name="recipeimage",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="recipes.recipe",
                verbose_name="model__foreign__recipe",
            ),
        ),
    ]
